[package]
name = "raproxy-capi"
version = "0.1.0"
authors = ["maciejkula <maciej.kula@gmail.com>"]

[lib]
name = "anna_capi"
crate-type = ["dylib"]

[dependencies]
anna = { path = "../anna/" }
libc = "0.2.19"
ndarray = "0.7.2"